### ISSUE TITLE
Code source de RafCalc

### ISSUE THREAD

**Issue by delthas** [Rafbor42/Rafbor42.github.io#1]
Bonjour,

Serait-il possible d'avoir le code source de RafCalc à proprement parler ? C'est à dire celui de [RafCalc.dll](https://github.com/Rafbor42/Rafbor42.github.io/blob/master/_framework/_bin/RafCalc.dll).

J'aimerais l'utiliser pour forker et me faire mon petit calculateur perso.

Merci

**Comment by Rafbor42** [comment]
Bonjour,
j'avais prévu de corriger un bug avant de poser le code source mais je n'en ai plus la volonté... J'essayerai de publier le code cet hiver.

**Comment by Rafbor42** [comment]
J'ai créé un nouveau dépôt [RafCalc](https://github.com/Rafbor42/RafCalc) dans lequel j'ai déposé les sources dans l'état, j'ai simplement adapté le projet pour qu'il cible le framework .NET6. Il fonctionne bien dans VSCode.
Je ne poursuivrai pas le développement, j'espère que quelqu'un prendra la suite ;)

**Comment by delthas** [comment]
OK merci !
